---

version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - cd job-app-01 && make ci && cd ${CODEBUILD_SRC_DIR}
      - cd job-app-02 && make ci && cd ${CODEBUILD_SRC_DIR}
