---

version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - echo -----------
      - pwd
      - echo -----------
      - cd job-app-01 && make ci
      - pwd
      - echo ========================
      - env
